### ISSUE TITLE
Parallelize RT Alignment

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li-lab/asari#70]

**Comment by shuzhao-li** [comment]
There should be a new module on RT alignment in ver 2, to
1) decide sample clusters, assuming that QC samples may not have the same properties as study samples.
2) enhance performance by parallelization.
3) accommodate user supplied internal standards and landmarks.
4) be compatible with GC data.

**Comment by jmmitc06** [comment]
The actual alignment is quite fast, its loading the data from disk that is slow which has been fixed largely with the newest versions. 

Point 1 can be done with clustering.
Point 3 can be pulled in from one of Steve's dev branches
Point 4 is work in progress.

**Comment by jmmitc06** [comment]
Going to close this issue since it was specifically about parallelization. The newest addition on the compress branch can preload files largely alleviating the bottleneck at both retention time alignment and mass grid construction.

**Comment by jmmitc06** [comment]
Had a minor epiphany, that since I'm I/O bound here, I don't need to parallelize the alignment actually. Previously I had the silly caching mechanism but I think for large studies, we can expect enough disk space and memory to handle say 4 files at a time. Amdahl's law would imply that we can get 90% of the performance but parallelizing this I/O bound step and leaving the LOWESS alignment (or whatever we do later) with a single core. This is so much simpler to manage than the mess that the caching was. Plus this is dask compatible as well and uses the unified parallelization utils. Chunk size is set from the CLI but defaults to 4.
