### ISSUE TITLE
Is online version of Asari working right now?

### ISSUE THREAD

**Issue by typewritermonkey** [shuzhao-li-lab/asari#81]
Hi, just checking if the online version is working right now? I tried submitting a couple of jobs but when I tried to retrieve them later it said "invalid task ID"

My task ID was RmSPYwL4_jBc_eYVpYzVAKg4z5jeWgBUrxyMW8GHatg

Also how long should we expect processing to take for 3 MZML files of around 250MB each?

Regards

Dan

**Comment by jmmitc06** [comment]
Hi Dan, 

The server, to the best of my knowledge, should be up and running. It seems to be working 

I admittedly do not use the web version for my own data processing; however, processing 3 files of that size should be _very_ fast. 

I just uploaded three files of my own for processing  (each about 25M) to try to replicate your issue. I'll let you know what I find.

**Comment by jmmitc06** [comment]
Dan, 

I think we have resolved this issue. Better messaging regarding the status of jobs will help with these issues in the future. So I'm going to close the issue. Feel free to reopen if you continue to have similar problems.
