### ISSUE TITLE
To include `_baseline_, noise_level` in mass track records 

### ISSUE THREAD

**Issue by shuzhao-li** [shuzhao-li-lab/asari#86]
for debugging and improvement

**Comment by jmmitc06** [comment]
Done in newest commit on gc_asari2. 

Mass track auditing is performed once during extraction but does not update the intensity vector. Currently auditing is done is stats_detect_peaks. It might be an improvement to audit during extraction and keep the updated intensities for later use but would need to confirm this is safe first.
