### ISSUE TITLE
documentation comments of `workflow.process_project()`

### ISSUE THREAD

**Issue by NchuYJ** [shuzhao-li-lab/asari#91]
`asari.workflow.process_project()` the function documentation comments hints it takes centroid MS data for batch processing, however, the function `single_sample_EICs_`  do this job uses pymzml.run.Reader(), which do not convert. Is this a mistake ?

![image](https://github.com/shuzhao-li-lab/asari/assets/83570131/1453f6bf-5900-47f3-ba94-d923ef22f5ce)

**Comment by jmmitc06** [comment]
The conversion to centroided data should be done before processing with asari. For instance, during the conversion from the vendor specific format to mzML.

Does this answer your question?

May 28, 2024 10:11:46 AM NchuYJ ***@***.***>:

**Comment by NchuYJ** [comment]
Hi Shuzhao-Li-Lab/Asari,

Thanks you for the answer, now it is clear.
