### ISSUE TITLE
Pickle size

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li-lab/asari#96]
this may be largely unavoidable; however, the pickles produced by processing certain types of data are very large, often 10x the size of the input mzML file. Ultimately, this limits the size of an analysis that can be performed on a regular machine. 

Largely opening this so I can associate it with the branch I will create to address this.

**Comment by jmmitc06** [comment]
Surprisingly compression works very very well on these pickles. Typical improvement in disk space is ~30x, (e.g., 877.7MB to 25.2MB for gzip) but the increase in processing time is noticeable during extraction. No compression requires 0.28 seconds to dump, compression is considerable slower: 55 seconds for gzip, 45 seconds for lzma. bz2 though requires 10 seconds and offers the best compression of the three with an output size of 17.3MB!!!!! Will implement this for version 2.

**Comment by shuzhao-li** [comment]
The use of pickle is to shift memory limit to I/O. Compression adds performance cost.
Asari currently goes back to the to extract peak area per sample. We may find a solution to get rid of pickles altogether.

**Comment by jmmitc06** [comment]
Marking this as closed as the compression is added to v1.14 for those who need it. V1.14 does not use caching and compression is disabled by default. Ultimately, if we use indexed mzML, we can probably just look up the right region in the mzML directly or something, eliminating pickle entirely. I'll roadmap that for v3.
